version: '3'
services:
  app:
    build:
      context: ./app
    ports:
      - "5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  nginx:
    build:
      context: ./nginx
      args:
        - APP_HOST=app
        - APP_PORT=5000
    ports:
      - "80:80"
    depends_on:
      - app


  

#version: "3.9"
#services:
#  app:
#    image: 1372022/devops-home-assignment
#    ports:
#      - "5000"
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#  nginx:
#    container_name: nginx
#    image: nginx-test
#    depends_on:
#      - app
#    ports:
#      - "80:80"
#