FROM nginx:latest

ARG APP_HOST
ARG APP_PORT

RUN echo "server { \n \
    listen 80; \n \
    location / { \n \
        proxy_set_header X-Real-IP \$remote_addr; \n \
        proxy_pass http://$APP_HOST:$APP_PORT; \n \
    } \n \
}" > /etc/nginx/conf.d/default.conf


