FROM nginx:latest

ARG APP_HOST
ARG APP_PORT

RUN echo "server { \n \
    listen 80; \n \
    location / { \n \
        proxy_set_header X-Real-IP \$remote_addr; \n \
        proxy_pass http://$APP_HOST:$APP_PORT; \n \
    } \n \
}" > /etc/nginx/conf.d/default.conf


job('example-job') {
    steps {
        git branch: 'master',
            credentialsId: 'my-credentials',
            url: 'https://github.com/amir-landau/jenkins-task.git'

        // Add ARG instructions and modify default.conf in one command
        bat '''
            echo "ARG APP_HOST" 
            \n 
            "ARG APP_PORT" \n
            RUN echo \"server { \n \
                listen 80; \n \
                location / { \n \
                    proxy_set_header X-Real-IP \$remote_addr; \n \
                    proxy_pass http://\$APP_HOST:\$APP_PORT; \n \
                } \n \
            }\" > /etc/nginx/conf.d/default.conf" > nginx/Dockerfile
        '''

        // build the Nginx container
        bat script: 'docker build -t my-nginx-image -f nginx/Dockerfile .',
         returnStatus: true
    }
}



#FROM nginx
#
#COPY nginx.conf /etc/nginx/
